### ISSUE TITLE
README a zsűrinek

### ISSUE THREAD

**Issue by Kevlaris** [GitEgylet-NEU/Ital-Automata#6]
- plusz funkciók feltüntetése
- ikonok származása (Google Fonts)
- egyéb..?

**Comment by DodgyDoma** [comment]
![kép](https://github.com/GitEgylet-NEU/Ital-Automata/assets/147428718/25a2fc75-3186-480f-bb6e-730e011032a2)

**Comment by Kevlaris** [comment]
https://github.com/GitEgylet-NEU/Ital-Automata/commit/de1bac7eef3f47c658ccbba8ebe2314a6dd30085
